# Generated by Django 5.0.6 on 2024-06-20 03:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileimage',
            field=models.ImageField(default='/media/default-profile.png', upload_to=accounts.models.productimages_path),
        ),
    ]
