# Generated by Django 5.0.6 on 2024-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certified',
            field=models.IntegerField(default=0),
        ),
    ]
