# Generated by Django 5.0.6 on 2024-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
