# Generated by Django 5.0.6 on 2024-06-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.IntegerField(default=0),
        ),
    ]
