# Generated by Django 5.0.6 on 2024-06-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.IntegerField(default=1),
        ),
    ]
