from django import forms
from .models import SavedAddress, SavedPayment
from accounts.models import CustomUser

class ProfileSettingsForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder": "Enter your username"}), required=False)
    email = forms.CharField(widget=forms.TextInput(attrs={"type":"email", "class":"form-control", "placeholder": "Enter your email address"}), required=False)
    profileimage = forms.ImageField(widget=forms.FileInput(attrs={'name':'img','id':'img','style':'display:none;'}),required=False)

    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "profileimage",
        )
        
class SavedAddressForm(forms.ModelForm):
    COUNTRIES = [
        ('Afghanistan', 'Afghanistan'),
        ('ÅlandIslands', 'ÅlandIslands'),
        ('Albania', 'Albania'),
        ('Algeria', 'Algeria'),
        ('AmericanSamoa', 'AmericanSamoa'),
        ('Andorra', 'Andorra'),
        ('Angola', 'Angola'),
        ('Anguilla', 'Anguilla'),
        ('Antarctica', 'Antarctica'),
        ('AntiguaandBarbuda', 'AntiguaandBarbuda'),
        ('Argentina', 'Argentina'),
        ('Armenia', 'Armenia'),
        ('Aruba', 'Aruba'),
        ('Australia', 'Australia'),
        ('Austria', 'Austria'),
        ('Azerbaijan', 'Azerbaijan'),
        ('Bahamas', 'Bahamas'),
        ('Bahrain', 'Bahrain'),
        ('Bangladesh', 'Bangladesh'),
        ('Barbados', 'Barbados'),
        ('Belarus', 'Belarus'),
        ('Belgium', 'Belgium'),
        ('Belize', 'Belize'),
        ('Benin', 'Benin'),
        ('Bermuda', 'Bermuda'),
        ('Bhutan', 'Bhutan'),
        ('Bolivia', 'Bolivia'),
        ('BosniaandHerzegovina', 'BosniaandHerzegovina'),
        ('Botswana', 'Botswana'),
        ('BouvetIsland', 'BouvetIsland'),
        ('Brazil', 'Brazil'),
        ('BritishIndianOceanTerritory', 'BritishIndianOceanTerritory'),
        ('BruneiDarussalam', 'BruneiDarussalam'),
        ('Bulgaria', 'Bulgaria'),
        ('BurkinaFaso', 'BurkinaFaso'),
        ('Burundi', 'Burundi'),
        ('Cambodia', 'Cambodia'),
        ('Cameroon', 'Cameroon'),
        ('Canada', 'Canada'),
        ('CapeVerde', 'CapeVerde'),
        ('CaymanIslands', 'CaymanIslands'),
        ('CentralAfricanRepublic', 'CentralAfricanRepublic'),
        ('Chad', 'Chad'),
        ('Chile', 'Chile'),
        ('China', 'China'),
        ('ChristmasIsland', 'ChristmasIsland'),
        ('Cocos(Keeling)Islands', 'Cocos(Keeling)Islands'),
        ('Colombia', 'Colombia'),
        ('Comoros', 'Comoros'),
        ('Congo', 'Congo'),
        ('Congo,TheDemocraticRepublicofThe', 'Congo,TheDemocraticRepublicofThe'),
        ('CookIslands', 'CookIslands'),
        ('CostaRica', 'CostaRica'),
        ("CoteD'ivoire", "CoteD'ivoire"),
        ('Croatia', 'Croatia'),
        ('Cuba', 'Cuba'),
        ('Cyprus', 'Cyprus'),
        ('CzechRepublic', 'CzechRepublic'),
        ('Denmark', 'Denmark'),
        ('Djibouti', 'Djibouti'),
        ('Dominica', 'Dominica'),
        ('DominicanRepublic', 'DominicanRepublic'),
        ('Ecuador', 'Ecuador'),
        ('Egypt', 'Egypt'),
        ('ElSalvador', 'ElSalvador'),
        ('EquatorialGuinea', 'EquatorialGuinea'),
        ('Eritrea', 'Eritrea'),
        ('Estonia', 'Estonia'),
        ('Ethiopia', 'Ethiopia'),
        ('FalklandIslands(Malvinas)', 'FalklandIslands(Malvinas)'),
        ('FaroeIslands', 'FaroeIslands'),
        ('Fiji', 'Fiji'),
        ('Finland', 'Finland'),
        ('France', 'France'),
        ('FrenchGuiana', 'FrenchGuiana'),
        ('FrenchPolynesia', 'FrenchPolynesia'),
        ('FrenchSouthernTerritories', 'FrenchSouthernTerritories'),
        ('Gabon', 'Gabon'),
        ('Gambia', 'Gambia'),
        ('Georgia', 'Georgia'),
        ('Germany', 'Germany'),
        ('Ghana', 'Ghana'),
        ('Gibraltar', 'Gibraltar'),
        ('Greece', 'Greece'),
        ('Greenland', 'Greenland'),
        ('Grenada', 'Grenada'),
        ('Guadeloupe', 'Guadeloupe'),
        ('Guam', 'Guam'),
        ('Guatemala', 'Guatemala'),
        ('Guernsey', 'Guernsey'),
        ('Guinea', 'Guinea'),
        ('Guinea-bissau', 'Guinea-bissau'),
        ('Guyana', 'Guyana'),
        ('Haiti', 'Haiti'),
        ('HeardIslandandMcdonaldIslands', 'HeardIslandandMcdonaldIslands'),
        ('HolySee(VaticanCityState)', 'HolySee(VaticanCityState)'),
        ('Honduras', 'Honduras'),
        ('HongKong', 'HongKong'),
        ('Hungary', 'Hungary'),
        ('Iceland', 'Iceland'),
        ('India', 'India'),
        ('Indonesia', 'Indonesia'),
        ('Iran,IslamicRepublicof', 'Iran,IslamicRepublicof'),
        ('Iraq', 'Iraq'),
        ('Ireland', 'Ireland'),
        ('IsleofMan', 'IsleofMan'),
        ('Israel', 'Israel'),
        ('Italy', 'Italy'),
        ('Jamaica', 'Jamaica'),
        ('Japan', 'Japan'),
        ('Jersey', 'Jersey'),
        ('Jordan', 'Jordan'),
        ('Kazakhstan', 'Kazakhstan'),
        ('Kenya', 'Kenya'),
        ('Kiribati', 'Kiribati'),
        ("Korea,DemocraticPeople'sRepublicof", "Korea,DemocraticPeople'sRepublicof"),
        ('Korea,Republicof', 'Korea,Republicof'),
        ('Kuwait', 'Kuwait'),
        ('Kyrgyzstan', 'Kyrgyzstan'),
        ("LaoPeople'sDemocraticRepublic", "LaoPeople'sDemocraticRepublic"),
        ('Latvia', 'Latvia'),
        ('Lebanon', 'Lebanon'),
        ('Lesotho', 'Lesotho'),
        ('Liberia', 'Liberia'),
        ('LibyanArabJamahiriya', 'LibyanArabJamahiriya'),
        ('Liechtenstein', 'Liechtenstein'),
        ('Lithuania', 'Lithuania'),
        ('Luxembourg', 'Luxembourg'),
        ('Macao', 'Macao'),
        ('Macedonia,TheFormerYugoslavRepublicof', 'Macedonia,TheFormerYugoslavRepublicof'),
        ('Madagascar', 'Madagascar'),
        ('Malawi', 'Malawi'),
        ('Malaysia', 'Malaysia'),
        ('Maldives', 'Maldives'),
        ('Mali', 'Mali'),
        ('Malta', 'Malta'),
        ('MarshallIslands', 'MarshallIslands'),
        ('Martinique', 'Martinique'),
        ('Mauritania', 'Mauritania'),
        ('Mauritius', 'Mauritius'),
        ('Mayotte', 'Mayotte'),
        ('Mexico', 'Mexico'),
        ('Micronesia,FederatedStatesof', 'Micronesia,FederatedStatesof'),
        ('Moldova,Republicof', 'Moldova,Republicof'),
        ('Monaco', 'Monaco'),
        ('Mongolia', 'Mongolia'),
        ('Montenegro', 'Montenegro'),
        ('Montserrat', 'Montserrat'),
        ('Morocco', 'Morocco'),
        ('Mozambique', 'Mozambique'),
        ('Myanmar', 'Myanmar'),
        ('Namibia', 'Namibia'),
        ('Nauru', 'Nauru'),
        ('Nepal', 'Nepal'),
        ('Netherlands', 'Netherlands'),
        ('NetherlandsAntilles', 'NetherlandsAntilles'),
        ('NewCaledonia', 'NewCaledonia'),
        ('NewZealand', 'NewZealand'),
        ('Nicaragua', 'Nicaragua'),
        ('Niger', 'Niger'),
        ('Nigeria', 'Nigeria'),
        ('Niue', 'Niue'),
        ('NorfolkIsland', 'NorfolkIsland'),
        ('NorthernMarianaIslands', 'NorthernMarianaIslands'),
        ('Norway', 'Norway'),
        ('Oman', 'Oman'),
        ('Pakistan', 'Pakistan'),
        ('Palau', 'Palau'),
        ('PalestinianTerritory,Occupied', 'PalestinianTerritory,Occupied'),
        ('Panama', 'Panama'),
        ('PapuaNewGuinea', 'PapuaNewGuinea'),
        ('Paraguay', 'Paraguay'),
        ('Peru', 'Peru'),
        ('Philippines', 'Philippines'),
        ('Pitcairn', 'Pitcairn'),
        ('Poland', 'Poland'),
        ('Portugal', 'Portugal'),
        ('PuertoRico', 'PuertoRico'),
        ('Qatar', 'Qatar'),
        ('Reunion', 'Reunion'),
        ('Romania', 'Romania'),
        ('RussianFederation', 'RussianFederation'),
        ('Rwanda', 'Rwanda'),
        ('SaintHelena', 'SaintHelena'),
        ('SaintKittsandNevis', 'SaintKittsandNevis'),
        ('SaintLucia', 'SaintLucia'),
        ('SaintPierreandMiquelon', 'SaintPierreandMiquelon'),
        ('SaintVincentandTheGrenadines', 'SaintVincentandTheGrenadines'),
        ('Samoa', 'Samoa'),
        ('SanMarino', 'SanMarino'),
        ('SaoTomeandPrincipe', 'SaoTomeandPrincipe'),
        ('SaudiArabia', 'SaudiArabia'),
        ('Senegal', 'Senegal'),
        ('Serbia', 'Serbia'),
        ('Seychelles', 'Seychelles'),
        ('SierraLeone', 'SierraLeone'),
        ('Singapore', 'Singapore'),
        ('Slovakia', 'Slovakia'),
        ('Slovenia', 'Slovenia'),
        ('SolomonIslands', 'SolomonIslands'),
        ('Somalia', 'Somalia'),
        ('SouthAfrica', 'SouthAfrica'),
        ('SouthGeorgiaandTheSouthSandwichIslands', 'SouthGeorgiaandTheSouthSandwichIslands'),
        ('Spain', 'Spain'),
        ('SriLanka', 'SriLanka'),
        ('Sudan', 'Sudan'),
        ('Suriname', 'Suriname'),
        ('SvalbardandJanMayen', 'SvalbardandJanMayen'),
        ('Swaziland', 'Swaziland'),
        ('Sweden', 'Sweden'),
        ('Switzerland', 'Switzerland'),
        ('SyrianArabRepublic', 'SyrianArabRepublic'),
        ('Taiwan', 'Taiwan'),
        ('Tajikistan', 'Tajikistan'),
        ('Tanzania,UnitedRepublicof', 'Tanzania,UnitedRepublicof'),
        ('Thailand', 'Thailand'),
        ('Timor-leste', 'Timor-leste'),
        ('Togo', 'Togo'),
        ('Tokelau', 'Tokelau'),
        ('Tonga', 'Tonga'),
        ('TrinidadandTobago', 'TrinidadandTobago'),
        ('Tunisia', 'Tunisia'),
        ('Turkey', 'Turkey'),
        ('Turkmenistan', 'Turkmenistan'),
        ('TurksandCaicosIslands', 'TurksandCaicosIslands'),
        ('Tuvalu', 'Tuvalu'),
        ('Uganda', 'Uganda'),
        ('Ukraine', 'Ukraine'),
        ('UnitedArabEmirates', 'UnitedArabEmirates'),
        ('UnitedKingdom', 'UnitedKingdom'),
        ('UnitedStates', 'UnitedStates'),
        ('UnitedStatesMinorOutlyingIslands', 'UnitedStatesMinorOutlyingIslands'),
        ('Uruguay', 'Uruguay'),
        ('Uzbekistan', 'Uzbekistan'),
        ('Vanuatu', 'Vanuatu'),
        ('Venezuela', 'Venezuela'),
        ('VietNam', 'VietNam'),
        ('VirginIslands,British', 'VirginIslands,British'),
        ('VirginIslands,U.S.', 'VirginIslands,U.S.'),
        ('WallisandFutuna', 'WallisandFutuna'),
        ('WesternSahara', 'WesternSahara'),
        ('Yemen', 'Yemen'),
        ('Zambia', 'Zambia'),
        ('Zimbabwe', 'Zimbabwe')
    ]
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','id':'billing-name','placeholder':'Enter name'}),max_length=100)
    email = forms.CharField(widget=forms.TextInput(attrs={"type":"email", "class":"form-control", "placeholder": "Enter email",'id':'billing-email-address'}),max_length=100)
    phone = forms.CharField(widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder": "Enter Phone no.",'id':'billing-phone'}),max_length=100)
    address = forms.CharField(widget=forms.Textarea(attrs={"rows":"3", "class":"form-control", "placeholder": "Enter full address",'id':'billing-address'}),max_length=100)
    country = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control form-select','title':'Country'}), choices=COUNTRIES,initial=COUNTRIES[230][0])
    city = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'form-control','id':'billing-city','placeholder':'Enter City'}),max_length=100)
    zipcode = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'form-control','id':'zip-code','placeholder':'Enter Postal code'}),max_length=100)
    
    class Meta:
        model = SavedAddress
        fields = ("name","email","phone","address","country","city","zipcode")

class SavedPaymentForm(forms.ModelForm):
    cardnumber = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'form-control'}),max_length=100, required=False)
    cardname = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'form-control'}),max_length=100, required=False)
    cardexp = forms.CharField(widget=forms.TextInput(attrs={'type':'text','class':'form-control','placeholder':'MM/YY'}),max_length=100, required=False)
    cardcvv = forms.CharField(widget=forms.TextInput(attrs={'type':'password','class':'form-control'}),max_length=100, required=False)
    paypalemail = forms.CharField(widget=forms.TextInput(attrs={'type':'email','class':'form-control'}),max_length=100, required=False)
    
    class Meta:
        model = SavedPayment
        fields = ("cardnumber","cardname","cardexp","cardcvv","paypalemail")
        
class PlanForm(forms.Form):
    plan = forms.IntegerField(widget=forms.HiddenInput(), required=False)
