# Generated by Django 5.0.6 on 2024-06-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpayment',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
