# Generated by Django 5.0.6 on 2024-06-19 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_comment_timeof_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timeof',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 14, 56, 52133)),
        ),
    ]
