# Generated by Django 5.0.6 on 2024-06-20 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comment_image1_alter_comment_timeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='helpfull',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timeof',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 3, 4, 33, 786652)),
        ),
    ]
