# Generated by Django 5.0.6 on 2024-06-22 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_comment_verified_remove_product_certified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timeof',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 3, 27, 13, 445203)),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.CharField(choices=[('EE', 'Everything Else'), ('Art', 'Art'), ('Baby', 'Baby'), ('Books', 'Books'), ('BI', 'Business & Industrial'), ('CP', 'Cameras & Photo'), ('CPA', 'Cell Phones & Accessories'), ('CSA', 'Clothing, Shoes & Accessories'), ('CTN', 'Computers/Tablets & Networking'), ('CE', 'Consumer Electronics'), ('Crafts', 'Crafts'), ('DB', 'Dolls & Bears'), ('DM', 'DVDs & Movies'), ('GCC', 'Gift Cards & Coupons'), ('HB', 'Health & Beauty'), ('HG', 'Home & Garden'), ('JW', 'Jewelry & Watches'), ('Music', 'Music'), ('MIG', 'Musical Instruments & Gear'), ('PS', 'Pet Supplies'), ('PG', 'Pottery & Glass'), ('RE', 'Real Estate'), ('SS', 'Specialty Services'), ('SG', 'Sporting Goods'), ('SMCFS', 'Sports Mem, Cards & Fan Shop'), ('TE', 'Tickets & Experiences'), ('TH', 'Toys & Hobbies'), ('Travel', 'Travel'), ('VGC', 'Video Games & Consoles')], default='Everything Else', max_length=100),
        ),
    ]
