# Generated by Django 5.0.6 on 2024-06-24 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_comment_timeof_alter_product_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timeof',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 18, 24, 33, 821647)),
        ),
    ]
