# Generated by Django 5.0.6 on 2024-06-24 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_comment_timeof_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timeof',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 23, 11, 45, 97712)),
        ),
    ]
